after-startup-command = []
start-at-login = true 

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 10

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
# on-focus-changed = ['move-mouse window-lazy-center']
automatically-unhide-macos-hidden-apps = false

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 3 
    inner.vertical =   3 
    outer.left =       3 
    outer.bottom =     3 
    outer.top =        3 
    outer.right =      3 

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-a = 'workspace A' # Anything | Uncategorized
    alt-b = 'workspace B' # Browser
    alt-c = 'workspace C' # Coding
    alt-d = 'workspace D' # Documents, Files
    alt-n = 'workspace N' # Notes 
    alt-r = 'workspace R' # Reading
    alt-s = 'workspace S' # System, Settings,...
    alt-t = 'workspace T' # Tools: DBeaver, Postman...
    alt-w = 'workspace W' # Work: Slack, GG Meet, MS Teams,...

    alt-shift-a = 'move-node-to-workspace A'
    alt-shift-b = 'move-node-to-workspace B'
    alt-shift-c = 'move-node-to-workspace C'
    alt-shift-d = 'move-node-to-workspace D'
    alt-shift-n = 'move-node-to-workspace N'
    alt-shift-r = 'move-node-to-workspace R'
    alt-shift-s = 'move-node-to-workspace S'
    alt-shift-t = 'move-node-to-workspace T'
    alt-shift-w = 'move-node-to-workspace W'

    alt-shift-f = 'fullscreen'
    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

### Coding ###
[[on-window-detected]]
if.app-id ='com.mitchellh.ghostty'
run = "move-node-to-workspace C"

### Browser ###
[[on-window-detected]]
if.app-id ='com.microsoft.edgemac'
run = "move-node-to-workspace B"

### Documents, Files ###
[[on-window-detected]]
if.app-id ='com.apple.finder'
run = "layout floating"

### System ###
[[on-window-detected]]
if.app-id ='com.apple.systempreferences'
run = "move-node-to-workspace S"

[[on-window-detected]]
if.app-id ='com.apple.ActivityMonitor'
run = "layout floating"

### Work ###
[[on-window-detected]]
if.app-id ='com.tinyspeck.slackmacgap'
run = "move-node-to-workspace W"

[[on-window-detected]]
if.app-id ='com.apple.Safari' # I use Safari for Teams ðŸ’€
run = "move-node-to-workspace W"

### Note ###
[[on-window-detected]]
if.app-id = 'com.apple.Notes'
run = "move-node-to-workspace N"

### Tools ###
[[on-window-detected]]
if.app-id ='org.jkiss.dbeaver.core.product'
run = "move-node-to-workspace T"

### Reading ###
[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = "move-node-to-workspace R"

### Anything ###
[[on-window-detected]]
if.app-id = 'com.vng.zalo'
run = "move-node-to-workspace A"

[[on-window-detected]]
if.app-id = 'com.vng.zalo.zalocall'
run = "move-node-to-workspace A"

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = "layout floating"
